// @generated by sisyphus-codegen (sisyphus-model → TS)，勿手改——改 model 后跑 `cargo run -p sisyphus-codegen -- gen`。
/// `ValidationCode` 镜像——校验规则码单一事实源在 `sisyphus-model/src/validate.rs`；
/// 本文件由 sisyphus-codegen 生成，勿手改。`cargo run -p sisyphus-codegen -- check` 校验漂移。
/// 前端 `validate.ts` 据此 emit `{ path, code, message }`，对账测试据此比码。

export const VALIDATION_CODES = [
  "required_parameter_default",
  "enum_choices",
  "when_workspace",
  "when_syntax",
  "shell_command_empty",
  "container_image_empty",
  "env_secret_collision",
  "artifact_upload_empty",
  "artifact_upload_absolute",
  "cache_key_empty",
  "cache_key_too_long",
  "cache_key_workspace",
  "cache_path_not_relative",
  "cache_files_glob",
] as const

export type ValidationCode = (typeof VALIDATION_CODES)[number]
