// @generated by sisyphus-codegen (sisyphus-model → TS)，勿手改——改 model 后跑 `cargo run -p sisyphus-codegen -- gen`。
/// Pipeline 三级结构 + 枚举 + tagged 形态——sisyphus-model 的 serde JSON 形态镜像
/// （ADR-0006/0009，票 B4-T7）。单一事实源在 `sisyphus-model/src/pipeline.rs`；
/// 本文件由 sisyphus-codegen 生成，勿手改。`cargo run -p sisyphus-codegen -- check` 校验漂移。
///
/// 与 `src/api/types.ts` 的关系：types.ts 的 `ModelPipeline` 等是只读页面的窄 DTO 子集；
/// 本文件是完整权威模型，供编辑器/前端校验消费。两者共存、不互替。

/** 参数类型（serde `rename_all=lowercase`）。 */
export type ParameterType = 'string' | 'number' | 'bool' | 'enum'

/** 参数值（serde `untagged`：单值）。 */
export type ParameterValue = string | number | boolean

/** shell 解释器偏好（serde `rename_all=lowercase`）。 */
export type Shell = 'sh' | 'bash' | 'pwsh' | 'cmd'

/** 环境变量键值对。 */
export interface EnvVar {
  name: string
  value: string
}

/** 通知配置（`on_success`/`recipients` serde `default` 无 skip → 永发）。 */
export interface Notification {
  on_success: boolean
  recipients: string[]
}

/** 修订版本。 */
export interface Revision {
  number: number
  operator: string
  at_ms: number
}

/** 产物上传声明。 */
export interface ArtifactUpload {
  name: string
  path: string
}

/** 产物下载依赖。 */
export interface ArtifactDownload {
  job: string
  name: string
  path: string
}

/** 缓存声明（`paths`/`files` serde `default` 无 skip → 永发，必填）。 */
export interface CacheSpec {
  key: string
  paths: string[]
  files: string[]
}

/** Pipeline 参数。 */
export interface Parameter {
  name: string
  type: ParameterType
  /** serde `default` 无 skip → 永发。 */
  required: boolean
  /** Option `skip_none` → 缺省时省略。 */
  default?: ParameterValue
  /** Option `skip_none` → 缺省时省略。 */
  description?: string
  /** Vec `skip_if_empty` → 空时省略。 */
  choices?: string[]
}

/** 执行环境（serde `tag=type, content=config`；`Host` 无 config）。 */
export type ExecutionEnv =
  | { type: 'host' }
  | { type: 'container'; config: { image: string } }

/** 步骤（serde `tag=type, content=config`）。 */
export type Step =
  | { type: 'shell'; config: { command: string; shell: Shell | null; when?: string } }
  | { type: 'checkout'; config: { submodules?: boolean; when?: string } }

/** 任务。 */
export interface Job {
  name: string
  /** Option `skip_none` → 缺省时省略。 */
  exec_env?: ExecutionEnv
  /** Vec `skip_if_empty` → 空时省略。 */
  labels?: string[]
  /** Option `skip_none` → 缺省时省略。 */
  when?: string
  /** Vec `skip_if_empty` → 空时省略。 */
  env?: EnvVar[]
  /** bool `skip_if_false` → 仅真时出现。 */
  allow_failure?: boolean
  /** u32 `skip_if_zero` → 仅非零时出现。 */
  retry_count?: number
  /** u32 `skip_if_zero` → 仅非零时出现。 */
  timeout_minutes?: number
  /** Vec `skip_if_empty` → 空时省略。 */
  artifact_uploads?: ArtifactUpload[]
  /** Vec `skip_if_empty` → 空时省略。 */
  artifact_downloads?: ArtifactDownload[]
  /** Vec `skip_if_empty` → 空时省略。 */
  caches?: CacheSpec[]
  /** Vec `skip_if_empty` → 空时省略。 */
  secrets?: string[]
  /** serde `default` 无 skip → 永发（空为 `[]`），必填。 */
  steps: Step[]
}

/** 阶段。 */
export interface Stage {
  name: string
  /** Option `skip_none` → 缺省时省略。 */
  when?: string
  /** serde `default` 无 skip → 永发（空为 `[]`），必填。 */
  jobs: Job[]
}

/** Pipeline 定义（三级结构）。 */
export interface Pipeline {
  name: string
  /** serde `default` 无 skip → 永发（空为 `[]`），必填。 */
  parameters: Parameter[]
  /** serde `default` 无 skip → 永发（空为 `[]`），必填。 */
  env: EnvVar[]
  /** Option `skip_none` → 缺省时省略。 */
  notification?: Notification
  /** serde `default` 无 skip → 永发（空为 `[]`），必填。 */
  stages: Stage[]
  /** Option `skip_none` → 缺省时省略。 */
  revision?: Revision
}
