// @generated by sisyphus-codegen (sisyphus-model → TS)，勿手改——改 model 后跑 `cargo run -p sisyphus-codegen -- gen`。
/// 扎根 sisyphus-model serde JSON 的类型化字面量——vue-tsc 据此对账 `pipeline.ts`
/// 的 TS 类型与 serde 形态（excess/missing/错 tag/错变体/null-where-required）。
///
/// 护栏非对称：抓不到「TS 标可选但 serde 永发」（如 `CacheSpec.paths`——present 总满足
/// optional）；该方向以 `pipeline.ts` 的 serde→TS 映射为准（人工评审）。
/// 本文件由 sisyphus-codegen 生成，勿手改。`cargo run -p sisyphus-codegen -- check` 校验漂移。

import type { Pipeline } from './pipeline'

export const valid_minimal: Pipeline = {
  env: [],
  name: "min",
  parameters: [],
  stages: [
    {
      jobs: [
        {
          name: "j",
          steps: []
        }
      ],
      name: "s"
    }
  ]
}

export const valid_full: Pipeline = {
  env: [
    {
      name: "CARGO_HOME",
      value: "${SISY_WORKSPACE}/.cargo"
    }
  ],
  name: "demo",
  notification: {
    on_success: true,
    recipients: [
      "dev@example.com",
      "ops@example.com"
    ]
  },
  parameters: [
    {
      default: "x",
      description: "字符串参数",
      name: "p_str",
      required: false,
      type: "string"
    },
    {
      default: 2.5,
      name: "p_num",
      required: true,
      type: "number"
    },
    {
      default: true,
      name: "p_bool",
      required: false,
      type: "bool"
    },
    {
      choices: [
        "a",
        "b"
      ],
      default: "a",
      name: "p_enum",
      required: false,
      type: "enum"
    },
    {
      name: "p_nodefault",
      required: false,
      type: "string"
    }
  ],
  revision: {
    at_ms: 1700000000000,
    number: 3,
    operator: "alice"
  },
  stages: [
    {
      jobs: [
        {
          allow_failure: true,
          artifact_downloads: [
            {
              job: "prep",
              name: "vendor",
              path: "vendor"
            }
          ],
          artifact_uploads: [
            {
              name: "bin",
              path: "target/release/sisyphus"
            }
          ],
          caches: [
            {
              files: [
                "Cargo.lock"
              ],
              key: "cargo-${SISY_BRANCH}",
              paths: [
                ".cargo"
              ]
            }
          ],
          env: [
            {
              name: "RUSTFLAGS",
              value: "-D warnings"
            }
          ],
          exec_env: {
            config: {
              image: "rust:1.97"
            },
            type: "container"
          },
          labels: [
            "sisyphus/os=linux"
          ],
          name: "compile",
          retry_count: 2,
          secrets: [
            "DOCKER_TOKEN"
          ],
          steps: [
            {
              config: {
                command: "cargo build --release",
                shell: "bash"
              },
              type: "shell"
            },
            {
              config: {
                command: "cargo test",
                shell: null,
                when: "${SISY_BRANCH} == \"main\""
              },
              type: "shell"
            },
            {
              config: {
                submodules: true
              },
              type: "checkout"
            },
            {
              config: {},
              type: "checkout"
            }
          ],
          timeout_minutes: 30,
          when: "exists SISY_COMMIT_ID"
        },
        {
          exec_env: {
            type: "host"
          },
          name: "prep",
          steps: []
        },
        {
          name: "lint",
          steps: [
            {
              config: {
                command: "sh -c 'echo sh'",
                shell: "sh"
              },
              type: "shell"
            },
            {
              config: {
                command: "pwsh -c 'echo pwsh'",
                shell: "pwsh"
              },
              type: "shell"
            },
            {
              config: {
                command: "cmd /c echo cmd",
                shell: "cmd"
              },
              type: "shell"
            }
          ]
        }
      ],
      name: "build",
      when: "${SISY_BRANCH} == \"main\""
    }
  ]
}
