/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildLogView: typeof import('./src/components/BuildLogView.vue')['default']
    EnvListEditor: typeof import('./src/components/editor/EnvListEditor.vue')['default']
    JobFormPanel: typeof import('./src/components/editor/JobFormPanel.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    ParametersTab: typeof import('./src/components/editor/ParametersTab.vue')['default']
    PipelineTrack: typeof import('./src/components/editor/PipelineTrack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
