//! OpenAPI 契约（utoipa 5，ADR-0005）：注解即契约，snapshot 守护防漂移
//! （`sisyphus-server/tests/openapi_snapshot.rs`）。

use utoipa::OpenApi;

use super::agents;
use super::artifacts;
use super::audit;
use super::auth;
use super::builds;
use super::error::{ErrorBody, ValidationIssue};
use super::health;
use super::logs;
use super::members;
use super::overview;
use super::pipelines;
use super::projects;
use super::scm;
use super::secrets;
use super::smtp_config;
use super::tokens;
use super::triggers;
use super::upgrade_packages;
use super::users;

/// Server REST API 契约。
///
/// Swagger UI 开发期（debug 构建）浏览：`/swagger-ui`；OpenAPI JSON：
/// `/api-docs/openapi.json`。
#[derive(OpenApi)]
#[openapi(
    info(
        title = "sisyphus Server API",
        version = env!("CARGO_PKG_VERSION"),
        description = "自托管 CI 平台 Server REST API。业务端点均在 /api/v1/ 前缀下；\
                       B2b 起会话认证全局把关（未认证一律 401，放行面仅 login/setup\
                       /healthz 与静态资源，票 B2b-T1）。",
    ),
    paths(
        health::healthz,
        overview::get,
        auth::setup,
        auth::login,
        auth::register,
        auth::logout,
        auth::me,
        auth::change_password,
        tokens::list,
        tokens::create,
        tokens::revoke,
        projects::list,
        projects::create,
        projects::get_one,
        scm::scm_probe,
        scm::scm_branches,
        scm::test_connection,
        scm::put_scm_credential,
        members::list,
        members::replace,
        secrets::list_secrets,
        secrets::put_secret,
        secrets::delete_secret,
        pipelines::get_definition,
        pipelines::put_definition,
        builds::trigger,
        builds::cancel,
        builds::rerun,
        builds::list,
        builds::detail,
        builds::remove,
        logs::stream,
        logs::download,
        artifacts::agent_upload,
        artifacts::agent_download,
        artifacts::list,
        artifacts::download,
        triggers::list,
        triggers::create,
        triggers::get_one,
        triggers::patch,
        users::list,
        users::create,
        users::patch,
        users::reset_password,
        users::directory,
        audit::list,
        smtp_config::get,
        smtp_config::put,
        agents::list,
        agents::create,
        agents::register,
        agents::get_one,
        agents::patch,
        agents::upgrade_all,
        agents::upgrade_one,
        agents::workspace_list,
        agents::workspace_clean,
        agents::cache_list,
        agents::cache_delete,
        upgrade_packages::upload,
        upgrade_packages::list,
        upgrade_packages::delete,
        upgrade_packages::download,
    ),
    components(schemas(
        health::Healthz,
        ErrorBody,
        ValidationIssue,
        overview::OverviewResponse,
        overview::QueueReason,
        overview::BuildsTerminalCounts,
        overview::Alerts,
        overview::RecentBuild,
        auth::CredentialsRequest,
        auth::MeResponse,
        auth::ChangePasswordRequest,
        tokens::CreateTokenRequest,
        tokens::TokenResponse,
        tokens::CreatedTokenResponse,
        projects::ScmTypeDto,
        projects::CreateProjectRequest,
        projects::ProjectResponse,
        scm::ScmProbeRequest,
        scm::ScmProbeResponse,
        scm::ScmBranchesRequest,
        scm::ScmBranchesResponse,
        scm::ScmBranch,
        scm::ScmCredentialRequest,
        members::RoleDto,
        members::MemberAssignment,
        members::MemberResponse,
        secrets::PutSecretRequest,
        secrets::SecretNameResponse,
        pipelines::PipelineDefinitionPayload,
        pipelines::PipelineDefinitionResponse,
        pipelines::SaveDefinitionResponse,
        builds::TriggerBuildRequest,
        builds::RerunBuildRequest,
        builds::BuildAcceptedResponse,
        builds::BuildSummaryResponse,
        builds::BuildListResponse,
        builds::BuildDetailResponse,
        builds::StageViewDto,
        builds::JobViewDto,
        builds::BuildStatusDto,
        builds::TriggerSourceDto,
        builds::JobStatusDto,
        builds::RerunModeDto,
        artifacts::ArtifactUploadedResponse,
        artifacts::ArtifactDto,
        artifacts::BuildArtifactsResponse,
        triggers::TriggerKindDto,
        triggers::CronSpecDto,
        triggers::PollSpecInputDto,
        triggers::CreateTriggerRequest,
        triggers::PatchTriggerRequest,
        triggers::TriggerResponse,
        users::UserResponse,
        users::CreateUserRequest,
        users::PatchUserRequest,
        users::ResetPasswordRequest,
        users::DirectoryEntryResponse,
        audit::AuditEntryResponse,
        smtp_config::SmtpConfigState,
        smtp_config::SmtpConfigResponse,
        smtp_config::SmtpConfigRequest,
        crate::store::smtp_config::SmtpTls,
        agents::CreateAgentRequest,
        agents::PatchAgentRequest,
        agents::AgentResponse,
        agents::CreatedAgentResponse,
        agents::RegisterAgentRequest,
        agents::RegisterAgentResponse,
        agents::VolumeUsageDto,
        agents::DiskUsageDto,
        agents::VersionDto,
        agents::UpgradeCommandRequest,
        agents::UpgradeIssuedSummary,
        agents::WorkspaceCleanRequest,
        agents::CacheDeleteRequest,
        agents::WorkspaceEntryDto,
        agents::WorkspaceListResponse,
        agents::CacheEntryDto,
        agents::CacheListResponse,
        upgrade_packages::UpgradePackageResponse,
    )),
    tags(
        (name = "infra", description = "探针与基础设施端点"),
        (name = "overview", description = "概览快照（票 B5-T7，ADR-0019：stat 卡全量真值 + 三类事实警示态 + 最近构建，喂 web 概览页；任意登录角色）"),
        (name = "auth", description = "认证与会话（setup wizard / register / login / logout / me / 自助改密）与 PAT（Bearer 通道，票 B2b-T3）"),
        (name = "projects", description = "项目管理（v1：list / create / get；成员三档角色分配，票 B2b-T5）"),
        (name = "scm", description = "SCM 探测 / 测试连接 / 分支枚举 / 凭据管理（票 B5-T3，ADR-0016：git ls-remote / svn info + ASKPASS 凭据递送，凭据不回显）"),
        (name = "secrets", description = "项目机密（票 B2b-T6：值只写不读——建/覆写、仅名清单、删；viewer/runner 连名不可见，项目 admin 档）"),
        (name = "pipelines", description = "Pipeline 定义读写（model 校验 + revision 语义）"),
        (name = "builds", description = "构建生命周期（票 B2c-T5：手动触发 / 取消 / 重跑 / 列表 / 详情；runner 档触发/取消/重跑、viewer 档列表/详情）"),
        (name = "artifacts", description = "产物链路（票 #74，ADR-0004/0007：Agent token 鉴权的上传/依赖拉取 + viewer 档的构建产物列表/流式下载）"),
        (name = "triggers", description = "触发器管理（票 B2c-T6，ADR-0016：cron / poll 触发源 CRUD；项目 admin 档——列/建/改配置与启停；触发历史经 builds 行呈现）"),
        (name = "users", description = "用户管理（全局 admin：建/列/禁用/重置，票 B2b-T4）与用户目录（项目 admin 的最小只读清单，票 B2b-T5）"),
        (name = "audit", description = "审计回放（票 B2b-T7：安全事件只增记账，仅全局 admin 可查询——按时间/用户/项目/事件类型过滤 + 分页）"),
        (name = "config", description = "全局配置（票 B5-T5：SMTP 发件配置——全局 admin 档；读脱敏 / 写全量 + 密码加密落库 + 变更入审计）"),
        (name = "agents", description = "Agent 注册面（票 B2c-T3：建条目/启停/编辑/详情——全局 admin 专属；token 与注册码明文仅在创建响应出现一次）"),
        (name = "upgrade-packages", description = "升级包管理（票 #76，ADR-0017：admin 上传/列表/删除 + Agent token 鉴权下载；文件名解析版本/目标三元组、窗口校验）"),
    )
)]
pub struct ApiDoc;
